### ISSUE TITLE
 babylond: command not found

### ISSUE THREAD

**Issue by Bloiney** [nopapername/shell-oooooyoung#1]
我用的是wsl2的环境，安装环境中也会有这个报错，在创建验证者身份的时候还是会有这个报错，是不是某个环境安装失败，还是有什么问题，我没有安装golang的开发环境

**Comment by nopapername** [comment]
golang环境要的，不过脚本会自动安装，可能是环境变量没应用上，试试 `source .bash_profile`

**Comment by nopapername** [comment]
> 我用的是wsl2的环境，安装环境中也会有这个报错，在创建验证者身份的时候还是会有这个报错，是不是某个环境安装失败，还是有什么问题，我没有安装golang的开发环境

@Bloiney Golang环境要的，不过脚本会自动安装，可能是环境变量没应用上，试试 `source .bash_profile`

**Comment by Bloiney** [comment]
> > 我用的是wsl2的环境，安装环境中也会有这个报错，在创建验证者身份的时候还是会有这个报错，是不是某个环境安装失败，还是有什么问题，我没有安装golang的开发环境
> 
> @Bloiney Golang环境要的，不过脚本会自动安装，可能是环境变量没应用上，试试 `source .bash_profile`

已解决，是环境变量问题
